backend:
  name: github
  repo: dillonfagan/co-op

media_folder: "/"
public_folder: "/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "/src/markdown-pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{title}}"
    fields:
      - {label: "Path", name: "path"}
      - {label: "Date", name: "date", default: "2020-01-01",  widget: "datetime"}
      - {label: "Title", name: "title", default: "New Post", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}